name: Python Package using Conda with PyTorch

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      # Use mamba for faster environment solving and package installation
      # It's highly recommended for PyTorch environments.
      run: |
        conda install mamba -n base -c conda-forge
        mamba env update --file environment.yml --name base
    - name: Install PyTorch
      # Install the appropriate PyTorch version based on CUDA availability
      # This example uses CPU-only PyTorch for simplicity and broader compatibility.
      # Adapt this section based on your needs (CUDA version, specific PyTorch build). 
      run: |
        conda activate base
        conda install pytorch torchvision torchaudio cpuonly -c pytorch
        # For CUDA, uncomment and adjust the following (specify CUDA toolkit version).
        # conda install pytorch torchvision torchaudio cudatoolkit=11.7 -c pytorch -c conda-forge 
    - name: Lint with flake8
      run: |
        conda activate base
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda activate base
        conda install pytest
        pytest
